const BOOKS = [
  {
    id: 1,
    title: "Thomas Kalkülüs: Cilt 1",
    author: "George B. Thomas",
    course: "Matematik I",
    category: "Mühendislik",
    price: "450 TL",
    condition: "Çok İyi",
    conditionLabel: "Sadece birkaç sayfası çizili.",
    icon: "ri-functions",
    gradient: "linear-gradient(to top right, #1e3a8a, #3b82f6)",
    sellerName: "Ahmet Yılmaz",
    timeAgo: "2 saat önce",
    description: "Mühendislik öğrencilerinin vazgeçilmezi. Kitap çok temiz durumda."
  },
  {
    id: 2,
    title: "Guyton ve Hall Tıbbi Fizyoloji",
    author: "John E. Hall",
    course: "Fizyoloji",
    category: "Tıp",
    price: "1200 TL",
    condition: "Yeni Gibi",
    conditionLabel: "Sıfır ayarında, hiç kullanılmadı.",
    icon: "ri-heart-pulse-line",
    gradient: "linear-gradient(to top right, #991b1b, #ef4444)",
    sellerName: "Selin Demir",
    timeAgo: "5 saat önce",
    description: "Tıp fakültesi için temel kaynak. İhtiyaç fazlası olduğu için satıyorum."
  },
  {
    id: 3,
    title: "Medeni Hukuk Başlangıç İlkeleri",
    author: "Kemal Oğuzman",
    course: "Medeni Hukuk",
    category: "Hukuk",
    price: "320 TL",
    condition: "İyi",
    conditionLabel: "Altı çizili satırlar mevcut.",
    icon: "ri-scales-3-line",
    gradient: "linear-gradient(to top right, #111827, #374151)",
    sellerName: "Burak Can",
    timeAgo: "1 gün önce",
    description: "Hukuk başlangıcı için en iyi kaynaklardan biri."
  },
  {
    id: 4,
    title: "Makroiktisat",
    author: "N. Gregory Mankiw",
    course: "İktisat 102",
    category: "İktisat",
    price: "280 TL",
    condition: "Eski",
    conditionLabel: "Kapakta hafif yıpranma var.",
    icon: "ri-line-chart-line",
    gradient: "linear-gradient(to top right, #065f46, #10b981)",
    sellerName: "Merve Aktaş",
    timeAgo: "3 saat önce",
    description: "İktisat temellerini anlamak için ideal bir yardımcı kitap."
  },
  {
    id: 5,
    title: "Organik Kimya",
    author: "Graham Solomons",
    course: "Kimya II",
    category: "Fen Bilimleri",
    price: "550 TL",
    condition: "Çok İyi",
    conditionLabel: "Tertemiz, notsuz.",
    icon: "ri-test-tube-line",
    gradient: "linear-gradient(to top right, #3730a3, #6366f1)",
    sellerName: "Emre Aydın",
    timeAgo: "12 saat önce",
    description: "Fen fakültesi öğrencileri için detaylı anlatımlı organik kimya."
  },
  {
    id: 6,
    title: "Neufert Yapı Tasarımı",
    author: "Ernst Neufert",
    course: "Mimari Proje",
    category: "Mimarlık",
    price: "950 TL",
    condition: "Yeni Gibi",
    conditionLabel: "Kapağı bile açılmadı.",
    icon: "ri-pencil-ruler-2-line",
    gradient: "linear-gradient(to top right, #451a03, #d97706)",
    sellerName: "Deniz Yıldız",
    timeAgo: "30 dakika önce",
    description: "Mimarların el kitabı. Proje dersleri için mutlaka lazım."
  },
  {
    id: 7,
    title: "Türk Edebiyatı Tarihi",
    author: "Ahmet Hamdi Tanpınar",
    course: "Edebiyat Tarihi",
    category: "Edebiyat",
    price: "180 TL",
    condition: "İyi",
    conditionLabel: "Sayfalarda sararma mevcut.",
    icon: "ri-quill-pen-line",
    gradient: "linear-gradient(to top right, #831843, #db2777)",
    sellerName: "Zeynep Koç",
    timeAgo: "4 gün önce",
    description: "Edebiyat araştırmacıları için klasik bir eser."
  },
  {
    id: 8,
    title: "Eğitim Psikolojisi",
    author: "Binnur Yeşilyaprak",
    course: "Pedagoji",
    category: "Eğitim",
    price: "150 TL",
    condition: "Çok İyi",
    conditionLabel: "Birkaç sayfası fosforlu kalemle çizili.",
    icon: "ri-user-voice-line",
    gradient: "linear-gradient(to top right, #0c4a6e, #0ea5e9)",
    sellerName: "Fatma Gül",
    timeAgo: "8 saat önce",
    description: "Öğretmen adayları için KPSS ve okul derslerine yardımcı."
  },
  {
    id: 9,
    title: "Statik ve Mukavemet",
    author: "Ferdinand Beer",
    course: "Statik",
    category: "Mühendislik",
    price: "400 TL",
    condition: "İyi",
    conditionLabel: "Kapak köşesi hafif bükülmüş.",
    icon: "ri-building-line",
    gradient: "linear-gradient(to top right, #1e3a8a, #3b82f6)",
    sellerName: "Murat Tekin",
    timeAgo: "2 gün önce",
    description: "İnşaat ve Makine mühendisliği için temel kaynak."
  },
  {
    id: 10,
    title: "Robbins Temel Patoloji",
    author: "Vinay Kumar",
    course: "Patoloji",
    category: "Tıp",
    price: "850 TL",
    condition: "Çok İyi",
    conditionLabel: "Çok temiz kullanıldı.",
    icon: "ri-microscope-line",
    gradient: "linear-gradient(to top right, #991b1b, #ef4444)",
    sellerName: "Ece Erdem",
    timeAgo: "1 gün önce",
    description: "Tıpta uzmanlık sınavı (TUS) için de uygun bir kaynak."
  },
  {
    id: 11,
    title: "Anayasa Hukuku",
    author: "Ergun Özbudun",
    course: "Anayasa",
    category: "Hukuk",
    price: "260 TL",
    condition: "Eski",
    conditionLabel: "Yoğun not alınmış sayfalar var.",
    icon: "ri-government-line",
    gradient: "linear-gradient(to top right, #111827, #374151)",
    sellerName: "Kaan Aras",
    timeAgo: "6 saat önce",
    description: "Notlar sınavda işinize yarayabilir, fiyatı uygun tuttum."
  },
  {
    id: 12,
    title: "Mikroiktisat Teorisi",
    author: "Walter Nicholson",
    course: "İktisat 201",
    category: "İktisat",
    price: "340 TL",
    condition: "Yeni Gibi",
    conditionLabel: "Etiketleri üzerinde.",
    icon: "ri-pie-chart-2-line",
    gradient: "linear-gradient(to top right, #065f46, #10b981)",
    sellerName: "Sude Naz",
    timeAgo: "22 saat önce",
    description: "İleri seviye iktisat teorisi için kapsamlı bir kitap."
  },
  {
    id: 13,
    title: "Genel Fizik 1",
    author: "Douglas Giancoli",
    course: "Fizik I",
    category: "Fen Bilimleri",
    price: "420 TL",
    condition: "İyi",
    conditionLabel: "Birkaç sayfasında su lekesi var.",
    icon: "ri-flashlight-line",
    gradient: "linear-gradient(to top right, #3730a3, #6366f1)",
    sellerName: "Caner Öz",
    timeAgo: "3 gün önce",
    description: "Mühendislik ve Fen fakülteleri için ortak kaynak."
  },
  {
    id: 14,
    title: "Mimarlık Tarihi",
    author: "Doğan Hasol",
    course: "Mimarlık Tarihi I",
    category: "Mimarlık",
    price: "210 TL",
    condition: "Çok İyi",
    conditionLabel: "Kitap kılıfı ile kullanıldı.",
    icon: "ri-ancient-gate-line",
    gradient: "linear-gradient(to top right, #451a03, #d97706)",
    sellerName: "Buse Tekin",
    timeAgo: "15 saat önce",
    description: "Mimarlık sanatı ve tarihine dair temel bilgiler."
  },
  {
    id: 15,
    title: "Ölçme ve Değerlendirme",
    author: "Turgut ve Baykul",
    course: "Ölçme Değerlendirme",
    category: "Eğitim",
    price: "190 TL",
    condition: "Yeni Gibi",
    conditionLabel: "Hiç kullanılmadı.",
    icon: "ri-ruler-2-line",
    gradient: "linear-gradient(to top right, #0c4a6e, #0ea5e9)",
    sellerName: "Ali Veli",
    timeAgo: "10 saat önce",
    description: "Eğitim fakültesi 3. sınıf ders kitabıdır."
  }
];
